-- Enable Extensions
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;

-- Create Tables
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    siret TEXT UNIQUE,
    email TEXT NOT NULL UNIQUE,
    owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    available_licenses INTEGER DEFAULT 0 NOT NULL,
    contact_preference BOOLEAN DEFAULT true,
    institution_settings JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    age INTEGER,
    gender TEXT,
    department TEXT,
    school TEXT,
    phone_number TEXT,
    avatar TEXT DEFAULT 'light',
    accent_color TEXT DEFAULT 'orange',
    home_preference TEXT DEFAULT 'questionnaire',
    company_id BIGINT REFERENCES public.companies(id) ON DELETE SET NULL,
    license_link_id BIGINT,
    license_active BOOLEAN DEFAULT false,
    contact_preference BOOLEAN DEFAULT true,
    is_recruiter BOOLEAN DEFAULT false,
    institution_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    avatar_json JSONB
);

ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS has_paid BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT,
    ADD COLUMN IF NOT EXISTS stripe_last_checkout_id TEXT,
    ADD COLUMN IF NOT EXISTS stripe_last_payment_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS public.class_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.license_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    class_group_id BIGINT REFERENCES public.class_groups(id) ON DELETE SET NULL,
    token TEXT UNIQUE NOT NULL,
    description TEXT,
    max_uses INTEGER DEFAULT 1,
    used_count INTEGER DEFAULT 0,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    custom_branding JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.profiles ADD CONSTRAINT fk_license_link_id FOREIGN KEY (license_link_id) REFERENCES public.license_links(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT PRIMARY KEY,
    content TEXT NOT NULL,
    category TEXT NOT NULL,
    questionnaire_type TEXT NOT NULL,
    interpretations JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE NOT NULL,
    response TEXT NOT NULL,
    questionnaire_type TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    questionnaire_type TEXT NOT NULL,
    personality_analysis TEXT,
    skills_assessment TEXT,
    job_recommendations JSONB,
    study_recommendations JSONB,
    formation_recommendations JSONB,
    skills_data JSONB,
    share_image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_letter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    email TEXT NOT NULL,
    content TEXT NOT NULL,
    send_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'scheduled',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure we can store multiple results per user, one per questionnaire_type
-- Drop legacy unique constraint on user_id if it exists, then add a composite unique
ALTER TABLE public.user_results DROP CONSTRAINT IF EXISTS user_results_user_id_key;
ALTER TABLE public.user_results
    ADD CONSTRAINT user_results_user_type_unique UNIQUE (user_id, questionnaire_type);

ALTER TABLE public.user_results
    ADD COLUMN IF NOT EXISTS share_image_url TEXT;

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    recipient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Global chat table
CREATE TABLE IF NOT EXISTS public.global_chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    user_email TEXT,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable realtime on the table (Supabase)
ALTER PUBLICATION supabase_realtime ADD TABLE public.global_chat;

CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    invoice_number TEXT UNIQUE NOT NULL,
    amount_cents INTEGER NOT NULL,
    license_quantity INTEGER NOT NULL,
    payment_id TEXT,
    payment_status TEXT DEFAULT 'pending',
    pdf_generated BOOLEAN DEFAULT false,
    pdf_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.custom_formations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    image_url TEXT,
    link TEXT,
    price FLOAT NOT NULL,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    required_answers JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.formation_france (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annee TEXT,
    etab_uai TEXT,
    etab_nom TEXT,
    tc TEXT,
    tf TEXT[],
    nm TEXT[],
    fl TEXT[],
    app TEXT,
    "int" TEXT,
    amg TEXT[],
    aut TEXT,
    region TEXT,
    departement TEXT,
    commune TEXT,
    fiche TEXT,
    dataviz TEXT,
    etab_url TEXT,
    nmc TEXT,
    gta TEXT,
    gti TEXT,
    etablissement_id_paysage TEXT,
    composante_id_paysage TEXT,
    rnd TEXT,
    code_formation TEXT,
    image TEXT,
    email TEXT,
    telephone TEXT,
    facebook TEXT,
    linkedin TEXT,
    youtube TEXT,
    geom geometry(Point, 4326)
);

create table public.metiers_france (
  id text null,
  intitule text null,
  description text null,
  dateactualisation timestamp without time zone null,
  romecode text null,
  typecontrat text null,
  experiencelibelle text null,
  dureetravaillibelle text null,
  dureetravaillibelleconverti text null,
  alternance boolean null,
  qualificationlibelle text null,
  secteuractivitelibelle text null,
  lieutravail_libelle text null,
  lieutravail_latitude double precision null,
  entreprise_nom text null,
  origineoffre_urlorigine text null,
  contact_urlpostulation text null,
  salaire_commentaire text null,
  entreprise_logo text null,
  contact_coordonnees1 text null,
  contextetravail_horaires text null,
  lieutravail_longitude double precision null
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.user_favorite_formations (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    formation_id BIGINT REFERENCES public.formation_france(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, formation_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.license_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_formations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.formation_france ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metiers_france ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_favorite_formations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_progression ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_chat ENABLE ROW LEVEL SECURITY;

-- Table to store extra information gathered from in-app dialogues
CREATE TABLE IF NOT EXISTS public.informations_complementaires (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    question_id TEXT NOT NULL,
    question_text TEXT NOT NULL,
    answer_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.informations_complementaires ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own extra info" ON public.informations_complementaires
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Create RLS Policies
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can manage their own progression" ON public.user_progression FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can view company data" ON public.companies FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Company owners can insert companies" ON public.companies FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Company owners can update their own company" ON public.companies FOR UPDATE USING (auth.uid() = owner_id);

CREATE POLICY "Authenticated users can view class groups" ON public.class_groups FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Company members can manage class groups" ON public.class_groups FOR ALL USING (
    (SELECT company.owner_id FROM public.companies AS company WHERE company.id = class_groups.company_id) = auth.uid()
);

CREATE POLICY "Authenticated users can view license links" ON public.license_links FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Company members can manage license links" ON public.license_links FOR ALL USING (
    (SELECT company.owner_id FROM public.companies AS company WHERE company.id = license_links.company_id) = auth.uid()
);

CREATE POLICY "Authenticated users can view questions" ON public.questions FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage their own responses" ON public.user_responses FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own results" ON public.user_results FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own favorite formations" ON public.user_favorite_formations FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own messages" ON public.messages FOR ALL USING (auth.uid() = sender_id OR auth.uid() = recipient_id);
CREATE POLICY "Anyone can read global chat" ON public.global_chat FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert their messages" ON public.global_chat FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Company members can view their invoices" ON public.invoices FOR SELECT USING (
    (SELECT company.owner_id FROM public.companies AS company WHERE company.id = invoices.company_id) = auth.uid()
);

CREATE POLICY "Authenticated users can view custom formations" ON public.custom_formations FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Company members can manage their custom formations" ON public.custom_formations FOR ALL USING (
    (SELECT company.owner_id FROM public.companies AS company WHERE company.id = custom_formations.company_id) = auth.uid()
);

CREATE POLICY "All users can view public formation and job data" ON public.formation_france FOR SELECT USING (true);
CREATE POLICY "All users can view public formation and job data" ON public.metiers_france FOR SELECT USING (true);

-- Create Functions and Triggers
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  avatar_data JSONB;
  questionnaire_data JSONB;
BEGIN
  -- Extract avatar and questionnaire data from user metadata
  avatar_data := new.raw_user_meta_data->'avatarData';
  questionnaire_data := new.raw_user_meta_data->'questionnaireResponses';
  
  -- Insert profile with avatar data
  INSERT INTO public.profiles (
    id, 
    first_name, 
    last_name, 
    age, 
    gender,
    department,
    school,
    phone_number,
    avatar,
    avatar_json
  )
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'prenom', ''),
    COALESCE(new.raw_user_meta_data->>'last_name', new.raw_user_meta_data->>'nom', ''),
    COALESCE((new.raw_user_meta_data->>'age')::INTEGER, 18),
    COALESCE(new.raw_user_meta_data->>'gender', new.raw_user_meta_data->>'genre', ''),
    COALESCE(new.raw_user_meta_data->>'department', new.raw_user_meta_data->>'departement', ''),
    COALESCE(new.raw_user_meta_data->>'school', new.raw_user_meta_data->>'ecole', ''),
    COALESCE(new.raw_user_meta_data->>'phone_number', new.raw_user_meta_data->>'numero_telephone', new.raw_user_meta_data->>'numeroTelephone', ''),
    COALESCE(avatar_data->>'url', avatar_data->>'provider', 'dicebear'),
    avatar_data
  );
  
  -- Insert questionnaire responses if provided
  IF questionnaire_data IS NOT NULL AND jsonb_typeof(questionnaire_data) = 'array' AND jsonb_array_length(questionnaire_data) > 0 THEN
    INSERT INTO public.user_responses (user_id, question_id, response, questionnaire_type)
    SELECT 
      new.id,
      (item->>'question_id')::BIGINT,
      item->>'answer',
      'inscription'
    FROM jsonb_array_elements(questionnaire_data) AS item
    WHERE (item->>'question_id') IS NOT NULL 
      AND (item->>'answer') IS NOT NULL
      AND (item->>'question_id')::TEXT ~ '^[0-9]+$';
  END IF;
  
  RETURN new;
EXCEPTION WHEN OTHERS THEN
  -- If anything fails, still allow user creation but log the error
  RAISE NOTICE 'Error in handle_new_user: %', SQLERRM;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_user_results_updated_at BEFORE UPDATE ON public.user_results FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Create Indexes for performance
CREATE INDEX IF NOT EXISTS idx_companies_owner_id ON public.companies(owner_id);
CREATE INDEX IF NOT EXISTS idx_profiles_company_id ON public.profiles(company_id);
CREATE INDEX IF NOT EXISTS idx_class_groups_company_id ON public.class_groups(company_id);
CREATE INDEX IF NOT EXISTS idx_license_links_company_id ON public.license_links(company_id);
CREATE INDEX IF NOT EXISTS idx_user_responses_user_id ON public.user_responses(user_id);
CREATE INDEX IF NOT EXISTS idx_user_responses_question_id ON public.user_responses(question_id);
CREATE INDEX IF NOT EXISTS idx_user_results_user_id ON public.user_results(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON public.messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_recipient_id ON public.messages(recipient_id);
CREATE INDEX IF NOT EXISTS idx_invoices_company_id ON public.invoices(company_id);
CREATE INDEX IF NOT EXISTS idx_custom_formations_company_id ON public.custom_formations(company_id);
CREATE INDEX IF NOT EXISTS idx_user_favorite_formations_user_id ON public.user_favorite_formations(user_id);
CREATE INDEX IF NOT EXISTS idx_user_favorite_formations_formation_id ON public.user_favorite_formations(formation_id);
CREATE INDEX IF NOT EXISTS idx_formation_france_geom ON public.formation_france USING GIST (geom);

CREATE TABLE IF NOT EXISTS public.user_progression (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    level INTEGER DEFAULT 1 NOT NULL,
    xp INTEGER DEFAULT 0 NOT NULL,
    quests JSONB DEFAULT '[]'::jsonb,
    perks JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.waitlist_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    email TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    source TEXT DEFAULT 'app',
    note TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    profile_snapshot JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table to store student grades by subject (Niveau 21)
CREATE TABLE IF NOT EXISTS public.user_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    subject TEXT NOT NULL,
    grade TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own notes" ON public.user_notes
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Table to store user selected fields/filieres (Niveau 21)
CREATE TABLE IF NOT EXISTS public.user_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    field_type TEXT NOT NULL,
    field_degree TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_fields ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own fields" ON public.user_fields
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Table to store user selected schools (Niveau 23)
CREATE TABLE IF NOT EXISTS public.user_schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    formation_id BIGINT REFERENCES public.formation_france(id) ON DELETE CASCADE,
    school_name TEXT NOT NULL,
    school_data JSONB,
    contact_accepted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_schools ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own schools" ON public.user_schools
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.waitlist_requests
    ADD CONSTRAINT waitlist_requests_user_id_key UNIQUE (user_id);

ALTER TABLE public.waitlist_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their waitlist entry" ON public.waitlist_requests
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their waitlist entry" ON public.waitlist_requests
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their waitlist entry" ON public.waitlist_requests
    FOR UPDATE USING (auth.uid() = user_id);

CREATE TRIGGER update_waitlist_requests_updated_at
    BEFORE UPDATE ON public.waitlist_requests
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ===================================================================
-- SECTION 3: IMPORT DATA INTO 'questions' TABLE
-- ===================================================================

INSERT INTO public.questions (id, content, category, questionnaire_type, interpretations)
VALUES
    (1, 'Tu aimes démonter, réparer ou bidouiller des objets pour voir comment ça marche ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers techniques, manuels, de réparation (mécanicien, électronicien, technicien de maintenance, ingénieur, métiers du bâtiment, etc.).", "Un peu": "Ouvre la porte à ces métiers mais avec d''autres options moins techniques (technico-commercial, designer produit, artisanat léger).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très techniques ou de réparation, mais peut garder ceux qui utilisent un peu de pratique (métiers créatifs ou artisanaux légers).", "Non": "Écarte les métiers techniques, manuels, de réparation. Oriente vers métiers intellectuels, relationnels, créatifs (marketing, RH, communication)."}'::jsonb),
    (2, 'Créer des vêtements stylés ou imaginer des looks tendance, ça te tente ?', 'Creation, Communication & Marketing', 'inscription', '{"Oui": "Favorise les métiers de la mode, du design, du stylisme, de la création artistique (styliste, designer de mode, conseiller en image, costumier, modéliste).", "Un peu": "Ouvre la porte aux métiers créatifs liés à l''apparence ou au design, mais laisse aussi d''autres domaines possibles (marketing de la mode, commerce de vêtements, community manager dans la mode).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers purement créatifs et liés à la mode, mais peut garder ceux qui croisent plusieurs domaines (ex : gestion de boutique, marketing).", "Non": "Écarte les métiers de la mode, du design vestimentaire, de la création artistique liée à l''apparence. Oriente vers des métiers techniques, relationnels ou intellectuels."}'::jsonb),
    (3, 'Ça te plairait de prendre les commandes d’un projet ou de motiver une équipe pour atteindre un objectif ?', 'Management & Business', 'inscription', '{"Oui": "Favorise les métiers de management, de gestion de projet, d''encadrement, d''entrepreneuriat (chef de projet, manager, directeur, coach, chef d''équipe, responsable d''association).", "Un peu": "Ouvre la porte aux métiers où il y a un peu de responsabilités ou de coordination sans être en première ligne (adjoint, assistant chef de projet, bras droit, animateur d''équipe).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers de leadership ou de forte responsabilité, mais peut garder ceux où le travail en équipe est important sans diriger (collaborateur, co-équipier, assistant).", "Non": "Écarte les métiers d''encadrement, de management, de direction. Oriente vers des métiers individuels, techniques, ou créatifs sans gestion d''équipe."}'::jsonb),
    (4, 'Défendre des gens, faire respecter la loi ou enquêter sur des affaires, ça te dirait ?', 'Security & Justice', 'inscription', '{"Oui": "Favorise les métiers liés à la justice, la sécurité, l''enquête, la défense des droits (avocat, policier, gendarme, juge, détective, éducateur spécialisé, travailleur social).", "Un peu": "Ouvre la porte à ces métiers mais aussi à ceux qui touchent indirectement à ces domaines (assistant juridique, médiateur, assistant social, métiers de la prévention).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers liés à la justice ou la sécurité, mais peut garder ceux qui ont une dimension d''accompagnement ou de conseil sans conflit (assistant social, conseiller d’orientation).", "Non": "Écarte les métiers juridiques, de sécurité, de défense des droits. Oriente vers des métiers plus créatifs, techniques ou relationnels sans lien avec la loi ou les enquêtes."}'::jsonb),
    (5, 'Tu aimes te débrouiller tout seul et prendre tes propres décisions au quotidien ?', 'Management & Business', 'inscription', '{"Oui": "Favorise les métiers autonomes, entrepreneuriaux, ou avec beaucoup de responsabilités individuelles (entrepreneur, freelance, artisan, consultant, développeur, photographe, commercial indépendant).", "Un peu": "Ouvre la porte à des métiers où un certain degré d''autonomie est nécessaire, tout en laissant la place au travail en équipe (chargé de projet, métiers du conseil, métiers artistiques).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très autonomes, mais conserve ceux où il y a un cadre et un collectif (assistant, collaborateur, employé dans une équipe).", "Non": "Écarte les métiers nécessitant de l''autonomie et de la prise d''initiative quotidienne. Oriente vers des métiers encadrés, avec supervision et travail en équipe (employé administratif, ouvrier, assistant)."}'::jsonb),
    (6, 'Tu te verrais bien faire plus de 3 années d’études pour décrocher le job de tes rêves ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers nécessitant des études longues ou spécialisées (médecin, ingénieur, avocat, architecte, chercheur, professeur, vétérinaire).", "Un peu": "Ouvre la porte à des métiers nécessitant des études modérées (Bac+3/Bac+4), comme cadre intermédiaire, chargé de mission, infirmier, éducateur spécialisé, designer.", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers nécessitant de longues études, mais garde ceux accessibles avec des formations courtes ou techniques (BTS, DUT, écoles spécialisées).", "Non": "Écarte les métiers demandant de longues études. Oriente vers des métiers accessibles rapidement (CAP, Bac pro, BTS, alternance), ou qui misent sur l''expérience plutôt que le diplôme (artisan, vendeur, commercial terrain)."}'::jsonb),
    (7, 'Tu te verrais bien faire plus de 6 années d’études pour décrocher le job de tes rêves ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers nécessitant des études très longues et spécialisées (médecin, chirurgien, avocat spécialisé, chercheur, professeur d’université, magistrat, vétérinaire, architecte diplômé).", "Un peu": "Ouvre la porte à ces métiers exigeants, mais laisse aussi la possibilité de viser des métiers accessibles avec un peu moins d''années d''études (ingénieur, cadre, consultant, métiers spécialisés Bac+5).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers nécessitant de très longues études, mais peut garder ceux nécessitant 3 à 5 ans (licence, master).", "Non": "Écarte les métiers nécessitant de longues études (plus de 6 ans). Oriente vers des métiers accessibles rapidement, avec formations courtes ou apprentissage (CAP, BTS, Bac+2/3, métiers manuels, commerciaux, techniques)."}'::jsonb),
    (8, 'Tu as souvent des idées originales et tu aimes créer des choses nouvelles ?', 'Creation, Communication & Marketing', 'inscription', '{"Oui": "Favorise les métiers créatifs, innovants et entrepreneuriaux (designer, inventeur, artiste, entrepreneur, créateur de contenu, directeur artistique, développeur, architecte).", "Un peu": "Ouvre la porte à des métiers créatifs mais avec des aspects plus pratiques ou de gestion (chef de produit, consultant en innovation, chef de projet, manager créatif).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très créatifs, mais garde ceux qui incluent un aspect pratique et créatif (responsable marketing, coordinateur de projets, gestionnaire de produit).", "Non": "Écarte les métiers créatifs, d''innovation ou de création artistique. Oriente vers des métiers plus structurés, analytiques ou relationnels (administratif, finance, vente, gestion)."}'::jsonb),
    (9, 'Comprendre les gens, les aider à travailler ensemble et gérer une équipe, ça te plairait ?', 'Management & Business', 'inscription', '{"Oui": "Favorise les métiers de gestion d’équipe, de ressources humaines et de leadership (manager, directeur, chef de projet, responsable RH, coach, recruteur, médiateur).", "Un peu": "Ouvre la porte aux métiers où la gestion d’équipe est importante, mais pas nécessairement à une échelle très large (coordinateur, animateur d''équipe, chargé de recrutement, responsable de groupe).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers de gestion d’équipe, mais garde ceux où la collaboration et la communication sont essentielles (responsable d’équipe de petite taille, collaborateur dans une équipe projet).", "Non": "Écarte les métiers nécessitant de gérer des équipes ou de prendre des responsabilités managériales. Oriente vers des métiers plus individuels ou techniques (comptable, analyste, artisan)."}'::jsonb),
    (10, 'Tu trouves ça passionnant d’explorer l’histoire et d’en apprendre plus sur différentes cultures ?', 'Culture, Humanities & Education', 'inscription', '{"Oui": "Favorise les métiers liés à l''histoire, l''archéologie, les sciences humaines et sociales (historien, archéologue, professeur, conservateur de musée, anthropologue, chercheur en sciences sociales).", "Un peu": "Ouvre la porte à des métiers liés à la culture, mais avec une dimension plus pratique ou de gestion (médiateur culturel, guide touristique, responsable de patrimoine, documentaliste, journaliste culturel).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très orientés vers l’histoire et les sciences humaines, mais garde ceux qui ont un aspect culturel ou éducatif (bibliothécaire, animateur, chargé de communication).", "Non": "Écarte les métiers liés à l''histoire, aux cultures et aux sciences sociales. Oriente vers des métiers plus techniques, scientifiques ou pratiques (ingénieur, comptable, commercial, technicien)."}'::jsonb),
    (11, 'Tu es du genre à aimer quand tout est bien fait et que chaque détail est parfait ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers qui demandent rigueur, précision et souci du détail (chef de projet, ingénieur, architecte, designer, contrôleur qualité, rédacteur, gestionnaire, comptable).", "Un peu": "Ouvre la porte à des métiers où la précision est importante, mais avec un peu moins de perfectionnisme nécessaire (responsable administratif, assistant de direction, gestionnaire de production, chef de produit).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers nécessitant une attention constante aux détails, mais garde ceux où une organisation et une structure sont importantes (collaborateur, employé de bureau, technicien).", "Non": "Écarte les métiers demandant une attention minutieuse aux détails. Oriente vers des métiers créatifs, interactifs ou plus flexibles (commercial, animateur, métiers du service)."}'::jsonb),
    (12, 'Tu aimes résoudre les problèmes en réfléchissant calmement et en suivant une logique ?', 'Science & Tech', 'inscription', '{"Oui": "Favorise les métiers analytiques, techniques et de résolution de problèmes (ingénieur, analyste, développeur, mathématicien, scientifique, consultant, conseiller en stratégie).", "Un peu": "Ouvre la porte aux métiers où il faut utiliser la logique et la réflexion, mais avec un aspect plus pratique ou moins théorique (technicien, responsable de projet, auditeur, gestionnaire de process).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très techniques ou analytiques, mais garde ceux qui nécessitent de la réflexion dans un contexte plus interactif (gestion, management, marketing).", "Non": "Écarte les métiers nécessitant une réflexion logique et analytique. Oriente vers des métiers créatifs, relationnels ou manuels (commercial, animateur, artisan, métiers du service)."}'::jsonb),
    (13, 'Tu aimerais travailler dans un endroit où tu rencontres des gens de différentes cultures et pays ?', 'Culture, Humanities & Education', 'inscription', '{"Oui": "Favorise les métiers internationaux, diplomatiques ou liés aux échanges interculturels (diplomate, consultant international, directeur des relations internationales, gestionnaire de projet à l''étranger, responsable des ressources humaines internationales).", "Un peu": "Ouvre la porte à des métiers où la diversité culturelle est présente, mais pas nécessairement au niveau international (responsable communication, chargé de mission multiculturelle, professeur de langues étrangères, journaliste, traducteur).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers internationaux, mais garde ceux où il y a des interactions avec des personnes de cultures variées (hôtellerie, tourisme, commerce international, relations publiques).", "Non": "Écarte les métiers nécessitant des échanges interculturels ou internationaux. Oriente vers des métiers locaux, plus centrés sur une seule culture ou une organisation fermée (métiers administratifs, techniques, commerciaux)."}'::jsonb),
    (14, 'Travailler dans le sport, que ce soit comme coach, éducateur ou autre, ça te plairait ?', 'Sport & Physical', 'inscription', '{"Oui": "Favorise les métiers liés au sport et à l''accompagnement physique (entraîneur, coach sportif, éducateur sportif, kinésithérapeute, préparateur physique, responsable sportif).", "Un peu": "Ouvre la porte aux métiers du sport mais aussi à des métiers qui en touchent les aspects organisationnels ou événementiels (gestionnaire d''événements sportifs, responsable marketing sportif, journaliste sportif).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers d''entraîneur ou d''éducateur sportif, mais garde ceux qui sont plus liés à l''organisation, la gestion ou la communication dans le domaine du sport (gestion de clubs, gestion des installations sportives).", "Non": "Écarte les métiers directement liés au sport ou à l''entraînement physique. Oriente vers des métiers plus intellectuels, créatifs ou commerciaux (marketing, vente, administration)."}'::jsonb),
    (15, 'Tu arrives à rester calme et à gérer quand les choses deviennent stressantes ou urgentes ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers à haute pression, nécessitant calme et gestion de crise (médecin, pompier, chirurgien, gestionnaire de crise, cadre dirigeant, avocat en droit pénal, chef de projet dans des secteurs à enjeux).", "Un peu": "Ouvre la porte à des métiers où la gestion du stress est importante, mais pas forcément dans des situations d’urgence immédiate (responsable d''équipe, commercial en environnement dynamique, analyste financier, gestionnaire de projet).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très stressants, mais garde ceux qui demandent une organisation dans un environnement exigeant mais moins urgent (assistant, coordinateur, gestionnaire de ressources humaines).", "Non": "Écarte les métiers nécessitant de gérer des situations stressantes ou urgentes. Oriente vers des métiers plus calmes ou où la pression est moins présente (administratif, comptable, métiers créatifs)."}'::jsonb),
    (16, 'Tu aimes apprendre des langues et découvrir comment les gens parlent dans d’autres pays ?', 'Culture, Humanities & Education', 'inscription', '{"Oui": "Favorise les métiers liés aux langues, à l''international et aux échanges culturels (traducteur, interprète, professeur de langues, diplomate, responsable des relations internationales, journaliste, consultant international).", "Un peu": "Ouvre la porte aux métiers où les langues sont importantes mais pas au centre, comme dans le commerce international, la gestion des ressources humaines ou le marketing à l''international.", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers où les langues sont une compétence clé, mais garde ceux où elles sont utiles en complément d''autres compétences (responsable export, gestionnaire de projets internationaux, gestionnaire de communautés).", "Non": "Écarte les métiers nécessitant une maîtrise des langues étrangères. Oriente vers des métiers moins axés sur les langues et plus sur des compétences techniques ou pratiques (gestion, comptabilité, métiers manuels)."}'::jsonb),
    (17, 'Tu aimes organiser tes affaires, planifier tes journées ou tes projets ?', 'Management & Business', 'inscription', '{"Oui": "Favorise les métiers liés à la gestion, l’organisation et la planification (chef de projet, gestionnaire, planificateur, coordinateur, directeur opérationnel, responsable logistique, organisateur d''événements).", "Un peu": "Ouvre la porte à des métiers qui nécessitent une certaine organisation, mais avec plus de flexibilité (assistant de gestion, responsable administratif, chargé de coordination, gestionnaire de production).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers nécessitant une organisation rigoureuse, mais garde ceux qui demandent de la structure sans être trop contraignants (commercial, employé administratif, ouvrier).", "Non": "Écarte les métiers demandant de l''organisation et de la planification. Oriente vers des métiers plus spontanés ou créatifs où la structure n’est pas aussi importante (artiste, technicien, service client)."}'::jsonb),
    (18, 'Tu es curieux de comprendre pourquoi les gens agissent de telle ou telle manière, ce qui se passe dans leur tête et comment ils réagissent ?', 'Culture, Humanities & Education', 'inscription', '{"Oui": "Favorise les métiers liés à la psychologie, aux sciences sociales et humaines (psychologue, psychiatre, sociologue, coach en développement personnel, psychothérapeute, conseiller en orientation).", "Un peu": "Ouvre la porte à des métiers où la compréhension du comportement humain est importante mais dans un cadre moins thérapeutique (ressources humaines, recrutement, médiateur, formateur, conseiller).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers de la psychologie et des sciences sociales, mais garde ceux où l’empathie et l’écoute sont utiles (commercial, manager, assistant social).", "Non": "Écarte les métiers nécessitant une compréhension approfondie du comportement humain. Oriente vers des métiers plus techniques ou analytiques où l''aspect humain est moins central (ingénieur, comptable, technicien)."}'::jsonb),
    (19, 'Travailler dans le domaine médical, que ce soit soigner des gens ou découvrir de nouvelles façons de les aider à aller mieux, ça te tente ?', 'Health & Medical', 'inscription', '{"Oui": "Favorise les métiers liés à la santé et aux soins (médecin, infirmier, chirurgien, pharmacien, chercheur médical, physiothérapeute, psychologue, médecin urgentiste).", "Un peu": "Ouvre la porte à des métiers médicaux mais avec une approche plus générale ou administrative (assistant médical, technicien de laboratoire, conseiller en santé, responsable qualité en milieu hospitalier).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très centrés sur le soin ou la recherche médicale, mais garde ceux qui sont liés à la santé publique, la prévention ou la gestion des soins (responsable des services de santé, administratif en milieu médical, responsable d''associations de santé).", "Non": "Écarte les métiers médicaux et de soins. Oriente vers des métiers plus techniques, commerciaux ou créatifs (designer, vendeur, gestionnaire)."}'::jsonb),
    (20, 'Prendre des décisions importantes en sachant qu’elles peuvent avoir de grandes conséquences te fait-il peur ?', 'Transversal', 'inscription', '{"Oui": "Oriente vers des métiers avec moins de pression décisionnelle, où les responsabilités sont plus limitées (employé administratif, assistant, technicien, ouvrier, chargé de mission avec supervision).", "Un peu": "Ouvre la porte à des métiers où il y a des responsabilités, mais avec un encadrement et une prise de décision partagée (responsable de projet, chef de petite équipe, commercial, analyste).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Favorise les métiers avec des responsabilités et des prises de décision, mais dans un environnement structuré (manager, gestionnaire de projet, directeur de département, consultant).", "Non": "Favorise les métiers où les décisions importantes font partie du rôle, sans hésitation (entrepreneur, cadre supérieur, directeur général, chef d’entreprise)."}'::jsonb),
    (21, 'Travailler dans un milieu artistique, comme la musique, le théâtre ou la création, ça te plairait ?', 'Creation, Communication & Marketing', 'inscription', '{"Oui": "Favorise les métiers créatifs et artistiques (musicien, acteur, réalisateur, scénariste, compositeur, danseur, artiste visuel, designer, photographe).", "Un peu": "Ouvre la porte à des métiers dans les secteurs artistiques mais avec un aspect plus organisationnel ou technique (producteur, directeur artistique, responsable de la communication artistique, régisseur, agent artistique).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers artistiques purs, mais garde ceux où la créativité est nécessaire sans être au cœur du métier (gestion de projets artistiques, marketing culturel, gestion de productions).", "Non": "Écarte les métiers dans le domaine artistique. Oriente vers des métiers plus structurés ou techniques (administratif, comptable, commercial, ingénieur)."}'::jsonb),
    (22, 'Tu aimerais faire un métier où tu protèges les autres, comme militaire, pompier ou policier ?', 'Security & Justice', 'inscription', '{"Oui": "Favorise les métiers liés à la sécurité, la protection et les interventions d’urgence (policier, pompier, militaire, garde du corps, secouriste, agent de sécurité, sauveteur en mer).", "Un peu": "Ouvre la porte aux métiers de la sécurité mais avec un aspect plus administratif ou de gestion (responsable de la sécurité, formateur en sécurité, consultant en sécurité, coordonnateur des risques).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers de protection directe, mais garde ceux qui sont liés à la gestion de la sécurité dans d’autres contextes (gestion des risques, sécurité informatique, responsable des ressources humaines en situation de crise).", "Non": "Écarte les métiers impliquant de protéger directement les autres. Oriente vers des métiers plus intellectuels ou créatifs (designer, technicien, cadre commercial)."}'::jsonb),
    (23, 'Tu aimerais travailler dans les fermes, cultiver des plantes ou créer des produits alimentaires ?', 'Environment & Agriculture', 'inscription', '{"Oui": "Favorise les métiers agricoles et de la production alimentaire (agriculteur, fermier, maraîcher, horticulteur, éleveur, transformateur alimentaire, ingénieur agronome).", "Un peu": "Ouvre la porte à des métiers liés à l’agriculture ou la production alimentaire, mais avec un aspect plus technique ou de gestion (technicien agricole, responsable de production alimentaire, gestionnaire d’exploitation agricole).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers directement liés à l’agriculture ou la production alimentaire, mais garde ceux qui sont liés à l’industrie alimentaire ou la distribution (responsable qualité alimentaire, distributeur, commercial dans le secteur agricole).", "Non": "Écarte les métiers agricoles ou liés à la production alimentaire. Oriente vers des métiers plus technologiques, créatifs ou commerciaux (ingénieur, designer, vendeur)."}'::jsonb),
    (24, 'Tu as une bonne mémoire pour te souvenir des petits détails et des infos importantes ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers nécessitant une grande capacité de mémorisation et de gestion de détails (avocat, médecin, archiviste, chercheur, analyste, rédacteur, gestionnaire de projet, responsable de la logistique).", "Un peu": "Ouvre la porte à des métiers où la mémoire est importante, mais avec un aspect plus dynamique ou pratique (commercial, assistant, technicien, responsable administratif).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers nécessitant une mémoire impeccable pour les détails, mais garde ceux où l''organisation et la gestion d’informations sont importantes (gestionnaire, responsable de la communication, coordinateur).", "Non": "Écarte les métiers où une bonne mémoire pour les détails est essentielle. Oriente vers des métiers plus pratiques ou créatifs, moins centrés sur la gestion d''informations détaillées (artiste, artisan, technicien)."}'::jsonb),
    (25, 'Tu te sens capable de faire plusieurs choses en même temps sans te perdre ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers nécessitant de la multitâche et de la gestion simultanée de plusieurs responsabilités (gestionnaire, chef de projet, responsable opérationnel, directeur, organisateur d’événements, secrétaire de direction, commercial, coordinateur).", "Un peu": "Ouvre la porte à des métiers où la multitâche est importante, mais dans un cadre moins exigeant (assistant, responsable de petites équipes, technicien, gestionnaire de petites tâches).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers de gestion multi-tâches, mais garde ceux où il faut gérer plusieurs activités sans trop de pression (employé administratif, responsable de la relation client, animateur).", "Non": "Écarte les métiers nécessitant de faire plusieurs choses en même temps. Oriente vers des métiers plus centrés sur une tâche à la fois ou plus pratiques (ouvrier, artisan, analyste)."}'::jsonb),
    (26, 'Tu aimes écrire, que ce soit des histoires, des textes ou exprimer tes idées sur papier ?', 'Creation, Communication & Marketing', 'inscription', '{"Oui": "Favorise les métiers liés à l''écriture et à la création littéraire (écrivain, journaliste, rédacteur, scénariste, auteur, éditeur, blogueur, copywriter).", "Un peu": "Ouvre la porte à des métiers où l’écriture est importante mais dans un cadre plus technique ou informatif (communicant, responsable de la rédaction de rapports, gestionnaire de contenu, chargé de communication).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers littéraires, mais garde ceux où l’écriture est utile dans un cadre moins créatif ou plus orienté vers la communication (gestion de projet, marketing, assistant administratif).", "Non": "Écarte les métiers nécessitant une écriture créative ou littéraire. Oriente vers des métiers plus pratiques ou techniques où l’écriture est moins centrale (technicien, ingénieur, commercial)."}'::jsonb),
    (27, 'Tu serais prêt à déménager dans une autre ville ou un autre pays pour un job ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers à l’international ou ceux qui nécessitent une mobilité géographique (consultant international, diplomate, responsable des ressources humaines à l’international, expatrié, manager d’équipe internationale, commercial à l’international, ingénieur de terrain).", "Un peu": "Ouvre la porte aux métiers qui impliquent des déplacements ou une mobilité mais pas nécessairement un déménagement permanent (technicien itinérant, commercial, organisateur d’événements internationaux, cadre en développement).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers nécessitant une grande mobilité, mais garde ceux qui impliquent des déplacements occasionnels ou des missions à court terme (responsable local, directeur de filiale, gestionnaire de projet).", "Non": "Écarte les métiers nécessitant de déménager. Oriente vers des métiers plus locaux ou sédentaires (assistant administratif, technicien, vendeur)."}'::jsonb),
    (28, 'Tu te vois bien réparer des ordinateurs ou t''occuper de problèmes techniques avec la technologie ?', 'Science & Tech', 'inscription', '{"Oui": "Favorise les métiers techniques et informatiques (technicien informatique, réparateur de matériel électronique, ingénieur en informatique, développeur, administrateur réseau, spécialiste en maintenance technique).", "Un peu": "Ouvre la porte aux métiers liés à la technologie et à la résolution de problèmes techniques, mais avec un aspect plus général ou administratif (support technique, gestionnaire de projet informatique, conseiller en technologie).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très techniques, mais garde ceux qui impliquent des compétences informatiques ou des connaissances de base en technologie (assistant technique, commercial dans le secteur tech, formateur en informatique).", "Non": "Écarte les métiers qui demandent une expertise technique en informatique ou en technologie. Oriente vers des métiers plus créatifs ou commerciaux (designer, gestionnaire, spécialiste marketing)."}'::jsonb),
    (29, 'Tu aimerais organiser des événements comme des festivals ou des expositions pour faire découvrir la culture ?', 'Creation, Communication & Marketing', 'inscription', '{"Oui": "Favorise les métiers de l’organisation d’événements culturels et artistiques (organisateur de festivals, directeur d''exposition, chargé de communication culturelle, directeur artistique, responsable événementiel, régisseur d''événements).", "Un peu": "Ouvre la porte à des métiers dans l''événementiel culturel, mais avec un aspect plus administratif ou technique (coordinateur d''événements, chargé de production, gestionnaire d’événements, responsable logistique).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers liés à l’organisation d’événements culturels, mais garde ceux qui sont plus orientés vers la gestion ou la communication (gestionnaire de projet culturel, marketing événementiel).", "Non": "Écarte les métiers dans l''événementiel culturel. Oriente vers des métiers plus sédentaires ou techniques (comptable, assistant, designer)."}'::jsonb),
    (30, 'Tu aimerais travailler dans les media, la création de vidéos, le montage ou le son pour des films ou des émissions ?', 'Creation, Communication & Marketing', 'inscription', '{"Oui": "Favorise les métiers créatifs dans les médias et la production audiovisuelle (réalisateur, monteur, ingénieur du son, réalisateur de films, vidéaste, journaliste, technicien du son, réalisateur de contenu digital).", "Un peu": "Ouvre la porte aux métiers dans la production audiovisuelle mais avec un aspect plus technique ou administratif (assistant réalisateur, producteur de contenu, chef de projet audiovisuel, régisseur, assistant technique en son ou image).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers purement créatifs dans l’audiovisuel, mais garde ceux qui impliquent une gestion ou une coordination dans le secteur des médias (responsable de la production, gestionnaire de projets multimédia, assistant de production).", "Non": "Écarte les métiers créatifs dans les médias. Oriente vers des métiers plus techniques ou administratifs (gestion, comptabilité, support technique)."}'::jsonb),
    (31, 'Tu aimerais créer et piloter quelque chose de nouveau de A à Z, comme ton propre projet ou une entreprise ?', 'Management & Business', 'inscription', '{"Oui": "Favorise les métiers d’entrepreneur et de gestion de projets innovants (créateur d’entreprise, fondateur de startup, chef de projet, directeur général, consultant, business developer, responsable de l''innovation).", "Un peu": "Ouvre la porte à des métiers où la gestion de projets est importante, mais dans un cadre plus encadré ou collaboratif (responsable de projets, chef de produit, coordinateur de projet, directeur de département).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers d’entrepreneur, mais garde ceux qui impliquent des responsabilités dans des projets, mais pas en tant que leader (assistant chef de projet, manager de petite équipe, coordinateur d’équipe).", "Non": "Écarte les métiers d’entrepreneur ou de gestion de projets complexes. Oriente vers des métiers plus exécutifs ou techniques où il n''y a pas besoin de gérer ou créer des projets de grande envergure (technicien, commercial, employé administratif)."}'::jsonb),
    (32, 'Tu aimes être en contact avec les gens et les aider à résoudre leurs besoins ou répondre à leurs questions ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers de service à la clientèle, du conseil et de l’accompagnement (commercial, conseiller client, coach, responsable du service client, chargé de communication, assistant social, psychologue, formateur).", "Un peu": "Ouvre la porte aux métiers impliquant des interactions avec les gens, mais avec une approche plus technique ou informatisée (support technique, gestionnaire de projet, conseiller en entreprise, assistant administratif).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers centrés sur le contact direct avec les gens, mais garde ceux où il y a un peu de gestion de relations humaines (responsable des ressources humaines, gestionnaire de services).", "Non": "Écarte les métiers impliquant un contact direct avec les gens. Oriente vers des métiers plus solitaires ou techniques (développeur, analyste, technicien)."}'::jsonb),
    (33, 'Tu te sens attiré par des métiers qui protègent l''environnement et qui te permettent de passer du temps dehors ?', 'Environment & Agriculture', 'inscription', '{"Oui": "Favorise les métiers liés à l''environnement, la nature et les activités extérieures (écologiste, garde forestier, agriculteur biologique, technicien en environnement, géographe, ingénieur en développement durable, spécialiste en gestion des ressources naturelles).", "Un peu": "Ouvre la porte à des métiers liés à l’environnement avec un aspect plus de gestion ou de coordination (responsable de projets environnementaux, conseiller en développement durable, consultant en gestion de l’environnement).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers extérieurs ou écologiques, mais garde ceux qui se concentrent sur la gestion de l’environnement à travers des tâches administratives ou techniques (gestionnaire d’environnement, assistant en développement durable, ingénieur en environnement).", "Non": "Écarte les métiers liés à l’environnement ou aux tâches extérieures. Oriente vers des métiers plus en intérieur ou plus techniques (comptable, administrateur, ingénieur, commercial)."}'::jsonb),
    (34, 'Tu aimerais créer des annonces ou des pubs pour faire connaître des produits et des idées ?', 'Creation, Communication & Marketing', 'inscription', '{"Oui": "Favorise les métiers dans la publicité, le marketing et la communication (créateur de publicité, directeur artistique, concepteur-rédacteur, responsable marketing, community manager, stratège en communication).", "Un peu": "Ouvre la porte aux métiers liés à la création publicitaire, mais avec un aspect plus stratégique ou analytique (responsable de campagne publicitaire, consultant en marketing, chargé de communication, gestionnaire de contenu).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers créatifs dans la publicité, mais garde ceux qui sont plus orientés vers l’analyse ou la gestion de projets (analyste marketing, gestionnaire de campagnes, responsable des relations publiques).", "Non": "Écarte les métiers créatifs dans la publicité. Oriente vers des métiers plus techniques ou administratifs (commercial, gestionnaire, analyste)."}'::jsonb),
    (35, 'Tu te sens capable de faire des métiers qui demandent de l’énergie et d’être actif toute la journée ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers physiques ou très actifs (ouvrier, coach sportif, pompier, militaire, agent de sécurité, livreur, travailleur sur chantier, animateur).", "Un peu": "Ouvre la porte aux métiers où l''activité physique est présente mais dans un cadre plus modéré ou équilibré (commercial terrain, éducateur sportif, technicien itinérant, responsable logistique).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers très physiques, mais garde ceux qui impliquent un peu de mouvement ou de déplacements (assistant de terrain, coordinateur d’événements, gestionnaire de projet).", "Non": "Écarte les métiers qui demandent beaucoup d’énergie physique. Oriente vers des métiers plus sédentaires ou intellectuels (bureau, gestion, analyse)."}'::jsonb),
    (36, 'Tu te sens bien quand tu dois parler devant des gens ou faire des présentations ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers qui nécessitent de prendre la parole en public (conférencier, formateur, avocat, présentateur, animateur, professeur, coach, leader d''équipe, responsable des relations publiques).", "Un peu": "Ouvre la porte à des métiers où la prise de parole est importante mais moins fréquente ou plus restreinte (responsable marketing, chef de projet, responsable communication, commercial).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers qui exigent des présentations régulières, mais garde ceux qui impliquent des interactions avec les gens (gestionnaire, responsable administratif, consultant).", "Non": "Écarte les métiers où il faut parler en public fréquemment. Oriente vers des métiers plus en retrait ou techniques (technicien, analyste, développeur)."}'::jsonb),
    (37, 'Tu aimes faire des expériences, comprendre le monde et découvrir de nouvelles choses grâce à la science ?', 'Science & Tech', 'inscription', '{"Oui": "Favorise les métiers scientifiques et de recherche (scientifique, chercheur, ingénieur, technicien de laboratoire, biologiste, chimiste, astrophysicien, data scientist).", "Un peu": "Ouvre la porte aux métiers où la curiosité scientifique est importante, mais avec une application plus pratique (technicien en recherche, assistant en laboratoire, consultant scientifique, analyste de données).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers de recherche pure, mais garde ceux qui impliquent des connaissances scientifiques appliquées ou techniques (ingénieur, gestionnaire de projets techniques, responsable R&D).", "Non": "Écarte les métiers scientifiques. Oriente vers des métiers plus pratiques ou créatifs où l’aspect scientifique n’est pas central (designer, commercial, manager)."}'::jsonb),
    (38, 'Tu aimerais transmettre ce que tu sais et aider les autres à apprendre ?', 'Culture, Humanities & Education', 'inscription', '{"Oui": "Favorise les métiers de l''enseignement, de la formation et de l''accompagnement (professeur, formateur, coach, éducateur, mentor, animateur pédagogique).", "Un peu": "Ouvre la porte aux métiers où la transmission de savoir est présente mais pas centrale (chef de projet, responsable d''équipe, consultant, chargé de formation interne).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers d''enseignement, mais garde ceux où un partage d''information ponctuel peut être utile (manager, assistant, coordinateur).", "Non": "Écarte les métiers de transmission de savoir et d''accompagnement. Oriente vers des métiers plus techniques ou créatifs sans dimension pédagogique (développeur, technicien, designer, analyste)."}'::jsonb),
    (39, 'Tu aimes te creuser la tête pour trouver des solutions à des problèmes difficiles ?', 'Transversal', 'inscription', '{"Oui": "Favorise les métiers d’analyse, d’ingénierie, de recherche et de résolution de problèmes (ingénieur, développeur, chercheur, consultant, analyste, architecte, data scientist, juriste, mathématicien).", "Un peu": "Ouvre la porte aux métiers qui demandent de réfléchir et d’analyser, mais de façon moins complexe ou plus encadrée (assistant chef de projet, technicien, chargé d''études, contrôleur de gestion).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers nécessitant de résoudre des problèmes complexes, mais garde ceux où il y a un minimum d’analyse ou de gestion (assistant, coordinateur, commercial).", "Non": "Écarte les métiers qui nécessitent beaucoup de réflexion et de résolution de problèmes difficiles. Oriente vers des métiers plus opérationnels, créatifs ou relationnels (vendeur, animateur, ouvrier, artiste)."}'::jsonb),
    (40, 'Tu aimes passer du temps sur les réseaux sociaux ou Youtube et créer ou partager du contenu ?', 'Creation, Communication & Marketing', 'inscription', '{"Oui": "Favorise les métiers liés au digital, aux réseaux sociaux et à la création de contenu (community manager, créateur de contenu, influenceur, responsable communication digitale, vidéaste, social media manager, copywriter).", "Un peu": "Ouvre la porte aux métiers liés aux réseaux sociaux avec un aspect plus stratégique ou occasionnel (chargé de communication, assistant marketing, responsable de projets digitaux, chargé de relations publiques).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers centrés sur la création de contenu, mais garde ceux où la communication en ligne est présente mais pas principale (assistant communication, gestionnaire de projet, consultant marketing).", "Non": "Écarte les métiers liés aux réseaux sociaux et à la création de contenu digital. Oriente vers des métiers plus techniques, créatifs hors digital ou de terrain (technicien, artisan, ingénieur, commercial terrain)."}'::jsonb),
    (41, 'Tu te sens à l’aise pour utiliser des outils en ligne et logiciels sur ordinateur ?', 'Science & Tech', 'inscription', '{"Oui": "Favorise les métiers du numérique, de la bureautique, de la tech et de la création digitale (développeur, graphiste, data analyst, community manager, chargé de communication digitale, designer, chef de projet digital, assistant administratif).", "Un peu": "Ouvre la porte aux métiers qui demandent une utilisation modérée des outils numériques (assistant de direction, chargé de clientèle, commercial, gestionnaire de projet).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers 100% numériques, mais garde ceux qui demandent un usage basique des outils (comptabilité, gestion, métiers manuels avec un peu de suivi administratif).", "Non": "Écarte les métiers qui reposent sur l’usage quotidien des outils en ligne ou logiciels. Oriente vers des métiers plus manuels, créatifs ou de terrain (artisan, ouvrier, animateur, agriculteur)."}'::jsonb),
    (42, 'Travailler dans le monde du luxe, comme la mode, les hôtels de prestige ou les produits haut de gamme, ça te tente ?', 'Transport & Tourism', 'inscription', '{"Oui": "Favorise les métiers liés au luxe, à la mode, à l’hôtellerie haut de gamme, au design et au commerce de produits de prestige (styliste, conseiller de vente luxe, chef de projet événementiel, designer, manager hôtelier, responsable communication luxe, chef cuisinier gastronomique).", "Un peu": "Ouvre la porte aux métiers liés au luxe, mais avec un aspect plus indirect (assistant marketing, assistant chef de produit, chargé de communication, responsable logistique pour marques haut de gamme).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers du luxe, mais garde ceux où la clientèle haut de gamme peut être une option (commercial, assistant administratif dans le secteur luxe, chargé de clientèle).", "Non": "Écarte les métiers liés au secteur du luxe. Oriente vers des métiers plus accessibles, techniques ou sociaux (artisan, technicien, éducateur, développeur)."}'::jsonb),
    (43, 'Tu t’intéresses aux sources d’énergies comme le soleil, le vent ou d’autres sources ?', 'Environment & Agriculture', 'inscription', '{"Oui": "Favorise les métiers liés aux énergies renouvelables, à la transition énergétique et à l’environnement (ingénieur en énergies renouvelables, technicien en énergie, consultant en développement durable, chargé de mission transition énergétique, chercheur en nouvelles énergies).", "Un peu": "Ouvre la porte aux métiers liés aux énergies, mais avec un aspect plus généraliste ou gestion de projet (chef de projet, assistant ingénieur, conseiller en environnement, chargé de développement durable).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers spécialisés en énergies, mais garde ceux où cet aspect peut être présent de façon indirecte (assistant administratif dans le secteur énergie, commercial en équipements techniques).", "Non": "Écarte les métiers liés aux énergies et à l’environnement. Oriente vers des métiers plus éloignés de ce secteur (communication, commerce, métiers créatifs, gestion)."}'::jsonb),
    (44, 'Aimerais-tu travailler avec des animaux, comme vétérinaire, soigneur ou dresseur ?', 'Environment & Agriculture', 'inscription', '{"Oui": "Favorise les métiers en contact direct avec les animaux (vétérinaire, soigneur animalier, dresseur, éducateur canin, toiletteur, assistant vétérinaire, éleveur, comportementaliste animalier).", "Un peu": "Ouvre la porte aux métiers liés aux animaux mais de manière plus indirecte ou ponctuelle (vendeur en animalerie, chargé de projet dans une association pour la protection animale, agent de parc naturel).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers centrés sur les animaux, mais garde ceux où le contact est rare ou accessoire (gestionnaire, assistant administratif dans une structure animalière).", "Non": "Écarte les métiers liés aux animaux. Oriente vers d''autres secteurs (commerce, industrie, communication, santé humaine, tech)."}'::jsonb),
    (45, 'Aimerais-tu dessiner des plans ou construire des bâtiments et des maisons en imaginant de nouveaux espaces ?', 'Science & Tech', 'inscription', '{"Oui": "Favorise les métiers liés à l’architecture, au bâtiment et à la construction (architecte, dessinateur en bâtiment, urbaniste, paysagiste, ingénieur en construction, conducteur de travaux, décorateur d’intérieur).", "Un peu": "Ouvre la porte aux métiers techniques ou de gestion de projets dans le secteur de la construction (technicien bureau d’études, assistant architecte, chef de chantier, assistant maître d’œuvre).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers de conception et de construction, mais garde ceux en lien indirect (commercial en immobilier, assistant administratif dans le bâtiment).", "Non": "Écarte les métiers liés à la construction et à la conception d’espaces. Oriente vers d''autres secteurs (santé, commerce, tech, social, art, communication)."}'::jsonb),
    (46, 'Est-ce que tu te sens attiré par la technologie comme la réalité virtuelle, l’intelligence artificielle ou la robotique ?', 'Science & Tech', 'inscription', '{"Oui": "Favorise les métiers liés aux nouvelles technologies, à la recherche et au développement tech (ingénieur en IA, développeur, roboticien, designer 3D, spécialiste réalité virtuelle, data scientist, chercheur en nouvelles technologies).", "Un peu": "Ouvre la porte aux métiers en lien avec la technologie mais plus accessibles ou plus orientés gestion (chef de projet tech, assistant en innovation, technicien en maintenance robotique, consultant numérique).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers 100% technologiques, mais garde ceux où la tech peut être un outil secondaire (marketing digital, support client tech, gestion de projet incluant de la technologie).", "Non": "Écarte les métiers liés à la technologie avancée. Oriente vers des métiers plus humains, créatifs ou manuels (social, commerce, santé, art, métiers de terrain)."}'::jsonb),
    (47, 'Tu aimerais conduire ou réparer des véhicules, comme des camions, des bus, ou même des voitures de course ?', 'Transport & Tourism', 'inscription', '{"Oui": "Favorise les métiers liés à la mécanique, au transport et à la conduite (mécanicien auto/moto, conducteur routier, chauffeur de bus, pilote, technicien en maintenance automobile, préparateur de véhicules de compétition).", "Un peu": "Ouvre la porte aux métiers liés aux véhicules mais de manière plus indirecte ou occasionnelle (conseiller en vente automobile, gestionnaire de flotte, contrôleur technique).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers centrés sur la mécanique ou la conduite, mais garde ceux où ces compétences peuvent être utiles de manière ponctuelle (logistique, gestion d''entrepôt).", "Non": "Écarte les métiers liés à la conduite ou la réparation de véhicules. Oriente vers d''autres secteurs (commerce, santé, tech, communication, art)."}'::jsonb),
    (48, 'Tu aimerais travailler dans un métier lié aux jeux vidéo, comme concepteur de jeux, programmeur ou testeur ?', 'Science & Tech', 'inscription', '{"Oui": "Favorise les métiers liés à l’industrie du jeu vidéo (développeur de jeux, concepteur de jeux vidéo, programmeur, game designer, testeur de jeux, animateur 3D, sound designer, scénariste pour jeux vidéo).", "Un peu": "Ouvre la porte aux métiers en lien avec les jeux vidéo, mais plus orientés vers la gestion, le marketing ou l’édition (chef de projet jeux vidéo, responsable marketing, community manager dans le secteur du jeu vidéo).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers créatifs dans le domaine des jeux vidéo, mais garde ceux où le secteur peut être plus secondaire (testeur qualité dans d''autres domaines, assistant administratif dans une entreprise de jeux).", "Non": "Écarte les métiers liés aux jeux vidéo. Oriente vers des métiers dans d''autres domaines créatifs ou techniques (design, communication, ingénierie, gestion)."}'::jsonb),
    (49, 'Est-ce que tu aimes faire des économies et gérer ton argent de poche de manière utile ?', 'Management & Business', 'inscription', '{"Oui": "Favorise les métiers liés à la gestion financière, à la comptabilité ou à l’investissement (comptable, conseiller financier, gestionnaire de patrimoine, analyste financier, banquier d''affaires, expert-comptable, trader).", "Un peu": "Ouvre la porte aux métiers liés à la gestion mais avec un aspect plus général ou administratif (gestionnaire de budget, assistant comptable, responsable des achats, analyste de données financières).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers purement financiers, mais garde ceux avec une gestion plus large ou stratégique des ressources (responsable administratif, manager de projet, commercial).", "Non": "Écarte les métiers liés à la finance. Oriente vers des métiers plus créatifs, humains ou techniques (design, marketing, secteur social, art, industrie)."}'::jsonb),
    (50, 'Est-ce que tu aimerais travailler dans un métier où tu prépares des repas pour les autres, comme un chef ou un pâtissier ?', 'Transport & Tourism', 'inscription', '{"Oui": "Favorise les métiers liés à la cuisine, à la pâtisserie et à la gastronomie (chef cuisinier, pâtissier, boulanger, cuisinier en collectivité, traiteur, responsable de restaurant, sommelier).", "Un peu": "Ouvre la porte aux métiers de la cuisine avec un aspect plus administratif ou gestionnaire (responsable de cuisine, assistant en restauration, gestionnaire de restaurant, consultant en alimentation).", "Je ne sais pas": "Laisse toutes les options ouvertes, sans privilégier ni exclure.", "Pas trop": "Écarte partiellement les métiers purement culinaires, mais garde ceux en lien avec le secteur de la restauration ou du service (serveur, responsable de salle, directeur de restauration).", "Non": "Écarte les métiers liés à la préparation des repas. Oriente vers d''autres secteurs (commerce, tech, marketing, design, santé)."}'::jsonb)
;

INSERT INTO public.questions (id, content, category, questionnaire_type, interpretations)
VALUES
    (51, 'Après une semaine chargée, préfères-tu sortir avec des amis pour te ressourcer ou passer une soirée tranquille chez toi ?', 'Transversal', 'mbti', '{}'),
    (52, 'Quand tu prends une décision, te bases-tu plutôt sur des faits concrets et vérifiables ou sur ton intuition et les possibilités futures ?', 'Transversal', 'mbti', '{}'),
    (53, 'Pour toi, est-il plus important d''être juste et objectif, même si cela peut blesser, ou d''être bienveillant et de préserver l''harmonie ?', 'Transversal', 'mbti', '{}'),
    (54, 'Préfères-tu avoir un plan bien défini et t''y tenir, ou garder tes options ouvertes et décider au fur et à mesure ?', 'Transversal', 'mbti', '{}'),
    (55, 'Dans un groupe, es-tu plutôt du genre à lancer la conversation ou à écouter attentivement les autres avant de parler ?', 'Transversal', 'mbti', '{}'),
    (56, 'Quand tu apprends quelque chose de nouveau, préfères-tu une approche pratique étape par étape ou une vue d''ensemble des concepts et des théories ?', 'Transversal', 'mbti', '{}'),
    (57, 'Face à un problème, as-tu tendance à l''analyser de manière logique et détachée ou à considérer l''impact humain et les sentiments des personnes concernées ?', 'Transversal', 'mbti', '{}'),
    (58, 'Concernant les délais, es-tu plus motivé par l''approche de la date limite ou préfères-tu finir tes tâches bien à l''avance ?', 'Transversal', 'mbti', '{}'),
    (59, 'Te sens-tu plus énergisé par les grandes foules et les événements sociaux ou par des interactions en petit comité ?', 'Transversal', 'mbti', '{}'),
    (60, 'Es-tu plus intéressé par ce qui est réel et observable ou par ce qui est possible et imaginaire ?', 'Transversal', 'mbti', '{}'),
    (61, 'Quand tu donnes ton avis, le fais-tu de manière directe et franche ou essaies-tu de le formuler avec tact et diplomatie ?', 'Transversal', 'mbti', '{}'),
    (62, 'Dans ton quotidien, aimes-tu que les choses soient organisées et structurées ou préfères-tu la spontanéité et la flexibilité ?', 'Transversal', 'mbti', '{}'),
    (63, 'As-tu tendance à penser à voix haute ou à réfléchir longuement en silence avant de partager tes idées ?', 'Transversal', 'mbti', '{}'),
    (64, 'Fais-tu plus confiance à ton expérience passée et aux faits qu''à des pressentiments ou des inspirations soudaines ?', 'Transversal', 'mbti', '{}'),
    (65, 'Est-ce que la critique constructive te motive à t''améliorer ou as-tu tendance à la prendre personnellement ?', 'Transversal', 'mbti', '{}'),
    (66, 'Un week-end idéal pour toi est-il plutôt planifié avec des activités précises ou laissé ouvert à l''improvisation ?', 'Transversal', 'mbti', '{}'),
    (67, 'Quand tu rencontres de nouvelles personnes, es-tu généralement celui qui engage la conversation ?', 'Transversal', 'mbti', '{}'),
    (68, 'Prêtes-tu plus d''attention aux détails concrets qu''aux schémas et aux significations cachées ?', 'Transversal', 'mbti', '{}'),
    (69, 'Tes décisions sont-elles plus souvent guidées par ta tête ou par ton cœur ?', 'Transversal', 'mbti', '{}'),
    (70, 'Considères-tu les règles et les horaires comme des cadres utiles ou comme des contraintes limitantes ?', 'Transversal', 'mbti', '{}'),
    (71, 'Dans ton travail, préfères-tu collaborer activement avec de nombreuses personnes ou travailler de manière indépendante ?', 'Transversal', 'mbti', '{}'),
    (72, 'Quand on te raconte une histoire, t''intéresses-tu davantage aux faits et à la séquence des événements ou au message sous-jacent et aux implications ?', 'Transversal', 'mbti', '{}'),
    (73, 'Pour résoudre un conflit, privilégies-tu une solution logique et équitable pour tous ou une solution qui préserve les bonnes relations ?', 'Transversal', 'mbti', '{}'),
    (74, 'Aimes-tu faire des listes de tâches et cocher les éléments au fur et à mesure, ou travailles-tu par à-coups, selon ton inspiration du moment ?', 'Transversal', 'mbti', '{}'),
    (75, 'Te décrirais-tu comme quelqu''un de sociable et facile à connaître ou comme quelqu''un de réservé et plus difficile à cerner ?', 'Transversal', 'mbti', '{}'),
    (76, 'Es-tu plus à l''aise avec des instructions claires et détaillées ou avec une vision globale et la liberté de trouver ta propre méthode ?', 'Transversal', 'mbti', '{}'),
    (77, 'Quand tu évalues le travail de quelqu''un, te concentres-tu sur la compétence et la correction ou sur l''effort et l''encouragement ?', 'Transversal', 'mbti', '{}'),
    (78, 'Le processus de prise de décision te semble-t-il plus satisfaisant que le résultat final, ou est-ce l''inverse ?', 'Transversal', 'mbti', '{}'),
    (79, 'Ton cercle d''amis est-il large avec de nombreuses connaissances ou plus restreint avec des liens profonds ?', 'Transversal', 'mbti', '{}'),
    (80, 'Quand tu imagines ton avenir, le vois-tu de manière concrète et réaliste ou de manière visionnaire et pleine de possibilités ?', 'Transversal', 'mbti', '{}'),
    (81, 'Penses-tu qu''il est plus important de dire la vérité, même si elle dérange, ou de préserver les sentiments des autres ?', 'Transversal', 'mbti', '{}'),
    (82, 'Te sens-tu plus à l''aise dans un environnement de travail prévisible et stable ou dans un environnement changeant et dynamique ?', 'Transversal', 'mbti', '{}'),
    (83, 'Après un événement social, te sens-tu plein d''énergie ou as-tu besoin de temps seul pour récupérer ?', 'Transversal', 'mbti', '{}'),
    (84, 'Lorsque tu observes une scène, remarques-tu d''abord les détails spécifiques ou l''ambiance générale ?', 'Transversal', 'mbti', '{}'),
    (85, 'En général, es-tu plus guidé par la logique et les principes ou par tes valeurs personnelles et tes émotions ?', 'Transversal', 'mbti', '{}'),
    (86, 'Préfères-tu régler les problèmes de manière définitive ou aimes-tu explorer différentes options avant de te décider ?', 'Transversal', 'mbti', '{}'),
    (87, 'Tu as tendance à partager facilement tes pensées et sentiments ou tu les gardes pour toi ?', 'Transversal', 'mbti', '{}'),
    (88, 'Le sens pratique est-il pour toi plus important que l''imagination ?', 'Transversal', 'mbti', '{}'),
    (89, 'Tu admires plus les gens pour leur clarté d''esprit ou pour leur compassion ?', 'Transversal', 'mbti', '{}'),
    (90, 'Le mélange du travail et du jeu te semble-t-il naturel ou préfères-tu les séparer clairement ?', 'Transversal', 'mbti', '{}');