import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { PGlite } from '@electric-sql/pglite'

const db = new PGlite()
const joris = '11111111-1111-4111-8111-111111111111'
const nicolas = '22222222-2222-4222-8222-222222222222'
const student = '33333333-3333-4333-8333-333333333333'
const partner = '44444444-4444-4444-8444-444444444444'

try {
  await db.exec(`
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE SCHEMA extensions;
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
      $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    CREATE FUNCTION public.unaccent(text) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT $1 $$;
    CREATE TABLE auth.users (id uuid PRIMARY KEY, email text, created_at timestamptz DEFAULT now(), last_sign_in_at timestamptz);
    CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users, first_name text, last_name text, age int,
      gender text, department text, school text, phone_number text, updated_at timestamptz DEFAULT now());
    CREATE TABLE public.companies (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text, email text,
      owner_id uuid REFERENCES auth.users, approved_at timestamptz, contact_first_name text, contact_last_name text,
      available_licenses int, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
    CREATE TABLE public.school_portal_members (company_id bigint, user_id uuid);
    CREATE TABLE public.custom_school_formations (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id bigint, title text NOT NULL, description text, diploma_level text, city text, domain text,
      image_url text, link text, contact_email text, is_published boolean DEFAULT true, updated_at timestamptz DEFAULT now());
    CREATE TABLE public.ecoles_partenaires (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_name text NOT NULL,
      formation_name text NOT NULL, city text NOT NULL, domain text, diploma_level text, description text, link text, contact_email text);
    CREATE TABLE public.contact_submitted (id uuid DEFAULT gen_random_uuid(), user_id uuid, formation_id uuid, submitted_at timestamptz);
    CREATE TABLE public.formation_france (id bigint PRIMARY KEY, etab_nom text);
    CREATE TABLE public.user_results (id bigint PRIMARY KEY, user_id uuid, questionnaire_type text,
      created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
    ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
    CREATE POLICY own_profile ON public.profiles FOR ALL TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
    ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
    CREATE POLICY own_company ON public.companies FOR ALL TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());
    ALTER TABLE public.contact_submitted ENABLE ROW LEVEL SECURITY;
    CREATE POLICY own_submission ON public.contact_submitted FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
    ALTER TABLE public.ecoles_partenaires ENABLE ROW LEVEL SECURITY;
    CREATE POLICY read_partners ON public.ecoles_partenaires FOR SELECT TO authenticated USING (true);
    GRANT USAGE ON SCHEMA public, auth TO authenticated, service_role, anon;
    GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles, public.companies, public.contact_submitted TO authenticated;
    GRANT SELECT ON public.ecoles_partenaires TO authenticated;
    INSERT INTO auth.users (id,email) VALUES
      ('${joris}','joris.geerdes@21datas.ch'), ('${nicolas}','nicolas.wiegele@zelia.io'), ('${student}','student@example.com');
    INSERT INTO auth.users(id,email) SELECT gen_random_uuid(), 'fixture-' || series || '@example.com' FROM generate_series(1,1001) series;
    INSERT INTO public.profiles(id,first_name) VALUES ('${student}','Original');
    INSERT INTO public.companies(name,email,owner_id) VALUES ('School','school@example.com','${student}');
    INSERT INTO public.formation_france VALUES(1,'School');
    INSERT INTO public.ecoles_partenaires(id,school_name,formation_name,city) VALUES('${partner}','School','Bachelor','Paris');
    INSERT INTO public.user_results(id,user_id,questionnaire_type) VALUES(1,'${student}','inscription');
  `)
  const migration = await readFile(new URL('../database/migration_backoffice.sql', import.meta.url), 'utf8')
  await db.exec(migration.replaceAll('nicolas.wiegele@zelia.io', 'nicolas.weigele@zelia.io'))
  await assert.rejects(db.query('SELECT public.backoffice_change($1,$2,$3,$4,$5)', [nicolas,'profile',student,JSON.stringify({ first_name: 'Nicolas' }),'Test']), /ADMIN_ACCESS_DENIED/)
  const emailCorrection = await readFile(new URL('../database/migration_backoffice_admin_email.sql', import.meta.url), 'utf8')
  await db.exec(emailCorrection)
  await db.exec(emailCorrection)
  await db.query('SELECT public.backoffice_change($1,$2,$3,$4,$5)', [nicolas,'profile',student,JSON.stringify({ first_name: 'Nicolas' }),'Test'])
  const auditPermissions = (await db.query("SELECT has_table_privilege('service_role','public.backoffice_audit','SELECT') AS read, has_table_privilege('service_role','public.backoffice_audit','INSERT') AS append, has_table_privilege('service_role','public.backoffice_audit','UPDATE,DELETE,TRUNCATE') AS modify")).rows[0]
  assert.deepEqual(auditPermissions,{ read:true,append:true,modify:false })
  const rpc = async (sql, parameters = []) => (await db.query(sql, parameters)).rows[0].result
  const users = await rpc('SELECT public.backoffice_users($1,$2,$3,$4,$5) AS result', ['', 'all', 'all', 50, 1000])
  assert.equal(users.total, 1004)
  assert.equal(users.items.length, 4)
  const overview = await rpc('SELECT public.backoffice_overview() AS result')
  assert.equal(overview.users, 1004)
  assert.equal(overview.results, 1)
  const results = await rpc('SELECT public.backoffice_results() AS result')
  assert.equal(results.items[0].email, 'student@example.com')
  const change = (kind, id, patch) => rpc('SELECT public.backoffice_change($1,$2,$3,$4,$5) AS result', [joris,kind,id,JSON.stringify(patch),'Test'])
  await change('profile',student,{ first_name: 'Corrected' })
  assert.equal((await db.query('SELECT first_name FROM profiles WHERE id=$1',[student])).rows[0].first_name,'Corrected')
  const auditBefore = (await db.query('SELECT count(*)::int AS count FROM backoffice_audit')).rows[0].count
  await assert.rejects(change('profile',student,{ contact_preference: true }), /INVALID_FIELD/)
  assert.equal((await db.query('SELECT count(*)::int AS count FROM backoffice_audit')).rows[0].count,auditBefore)
  await change('school_approve','1',{})
  assert.ok((await db.query('SELECT approved_at FROM companies')).rows[0].approved_at)
  assert.deepEqual((await db.query("SELECT changed_fields FROM backoffice_audit WHERE action='update:school_approve'")).rows[0].changed_fields,['approved_at'])
  const custom = await change('custom',null,{ company_id: 1, title: 'Private formation' })
  await change('custom',String(custom.id),{ is_published: false })
  await change('partner',partner,{ is_active: false })
  await assert.rejects(db.query('SELECT public.backoffice_submit_partner($1,$2)',[student,partner]), /PARTNER_UNAVAILABLE/)
  await change('partner',partner,{ is_active: true })
  await db.query('SELECT public.backoffice_submit_partner($1,$2)',[student,partner])
  await change('partner',partner,{ is_active: false })
  assert.equal((await db.query('SELECT count(*)::int AS count FROM contact_submitted')).rows[0].count,1)
  await assert.rejects(change('partner',partner,{ school_name: 'Renamed' }), /CANONICAL_SCHOOL_NAME_READ_ONLY/)
  const asStudent = async (sql) => {
    await db.exec(`SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub','${student}',false);`)
    try { return await db.query(sql) } finally { await db.exec('RESET ROLE') }
  }
  await assert.rejects(asStudent('SELECT public.backoffice_users()'), /permission denied/)
  await assert.rejects(asStudent('SELECT * FROM public.backoffice_account_suspensions'), /permission denied/)
  await assert.rejects(asStudent("UPDATE companies SET approved_at=now() WHERE id=1"), /permission denied/)
  await assert.rejects(asStudent(`INSERT INTO contact_submitted(user_id,formation_id) VALUES('${student}','${partner}')`), /row-level security/)
  await asStudent("UPDATE companies SET contact_first_name='Contact' WHERE id=1")
  const pending = await rpc('SELECT public.backoffice_account_change($1,$2,$3,$4) AS result',[joris,student,true,'Test suspension'])
  assert.equal(pending.is_suspended,true)
  assert.equal((await asStudent('SELECT * FROM profiles')).rows.length,0)
  await assert.rejects(asStudent(`INSERT INTO profiles(id) VALUES('${student}')`),/row-level security/)
  await assert.rejects(rpc('SELECT public.backoffice_account_change($1,$2,$3,$4) AS result',[joris,nicolas,true,'Forbidden']),/PROTECTED_ADMIN_ACCOUNT/)
  const restoring = await rpc('SELECT public.backoffice_account_change($1,$2,$3,$4) AS result',[joris,student,false,'Test reactivation'])
  assert.equal(restoring.is_suspended,true)
  await assert.rejects(rpc('SELECT public.backoffice_account_change($1,$2,$3,$4,$5) AS result',[joris,student,true,'Stale',pending.revision]),/ACCOUNT_STATE_CHANGED/)
  await rpc('SELECT public.backoffice_account_change($1,$2,$3,$4,$5) AS result',[joris,student,false,'Test reactivation',restoring.revision])
  assert.equal((await asStudent('SELECT * FROM profiles')).rows.length,1)
  await change('school_revoke','1',{})
  assert.equal((await db.query('SELECT approved_at FROM companies')).rows[0].approved_at,null)
  console.log('Back-office PostgreSQL functions, pagination >1000, atomic audit, suspension and RLS verified.')
} finally {
  await db.close()
}