import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { PGlite } from '@electric-sql/pglite'

const db = new PGlite()
const joris = '11111111-1111-4111-8111-111111111111'
const nicolas = '22222222-2222-4222-8222-222222222222'
const student = '33333333-3333-4333-8333-333333333333'
const partner = '44444444-4444-4444-8444-444444444444'

try {
  await db.exec(`
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE SCHEMA extensions;
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
      $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    CREATE FUNCTION public.unaccent(text) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT $1 $$;
    CREATE TABLE auth.users (id uuid PRIMARY KEY, email text, created_at timestamptz DEFAULT now(), last_sign_in_at timestamptz);
    CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users, first_name text, last_name text, age int,
      gender text, department text, school text, phone_number text, updated_at timestamptz DEFAULT now());
    CREATE TABLE public.companies (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text, email text,
      owner_id uuid REFERENCES auth.users, approved_at timestamptz, contact_first_name text, contact_last_name text,
      available_licenses int, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
    CREATE TABLE public.school_portal_members (company_id bigint, user_id uuid);
    CREATE TABLE public.custom_school_formations (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id bigint, title text NOT NULL, description text, diploma_level text, city text, domain text,
      image_url text, link text, contact_email text, is_published boolean DEFAULT true, updated_at timestamptz DEFAULT now());
    CREATE TABLE public.ecoles_partenaires (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_name text NOT NULL,
      formation_name text NOT NULL, city text NOT NULL, domain text, diploma_level text, description text, link text, contact_email text);
    CREATE TABLE public.contact_submitted (id uuid DEFAULT gen_random_uuid(), user_id uuid, formation_id uuid, submitted_at timestamptz);
    CREATE TABLE public.formation_france (id bigint PRIMARY KEY, etab_nom text);
    CREATE TABLE public.user_results (id bigint PRIMARY KEY, user_id uuid, questionnaire_type text,
      created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
    ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
    CREATE POLICY own_profile ON public.profiles FOR ALL TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
    ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
    CREATE POLICY own_company ON public.companies FOR ALL TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());
    ALTER TABLE public.contact_submitted ENABLE ROW LEVEL SECURITY;
    CREATE POLICY own_submission ON public.contact_submitted FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
    ALTER TABLE public.ecoles_partenaires ENABLE ROW LEVEL SECURITY;
    CREATE POLICY read_partners ON public.ecoles_partenaires FOR SELECT TO authenticated USING (true);
    GRANT USAGE ON SCHEMA public, auth TO authenticated, service_role, anon;
    GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles, public.companies, public.contact_submitted TO authenticated;
    GRANT SELECT ON public.ecoles_partenaires TO authenticated;
    INSERT INTO auth.users (id,email) VALUES
      ('${joris}','joris.geerdes@21datas.ch'), ('${nicolas}','nicolas.wiegele@zelia.io'), ('${student}','student@example.com');
    INSERT INTO auth.users(id,email) SELECT gen_random_uuid(), 'fixture-' || series || '@example.com' FROM generate_series(1,1001) series;
    INSERT INTO public.profiles(id,first_name) VALUES ('${student}','Original');
    INSERT INTO public.companies(name,email,owner_id) VALUES ('School','school@example.com','${student}');
    INSERT INTO public.formation_france VALUES(1,'School');
    INSERT INTO public.ecoles_partenaires(id,school_name,formation_name,city) VALUES('${partner}','School','Bachelor','Paris');
    INSERT INTO public.user_results(id,user_id,questionnaire_type) VALUES(1,'${student}','inscription');
  `)
  const migration = await readFile(new URL('../database/migration_backoffice.sql', import.meta.url), 'utf8')
  await db.exec(migration.replaceAll('nicolas.wiegele@zelia.io', 'nicolas.weigele@zelia.io'))
  await assert.rejects(db.query('SELECT public.backoffice_change($1,$2,$3,$4,$5)', [nicolas,'profile',student,JSON.stringify({ first_name: 'Nicolas' }),'Test']), /ADMIN_ACCESS_DENIED/)
  const emailCorrection = await readFile(new URL('../database/migration_backoffice_admin_email.sql', import.meta.url), 'utf8')
  await db.exec(emailCorrection)
  await db.exec(emailCorrection)
  const partnerResultsMigration = await readFile(new URL('../database/migration_backoffice_partner_results.sql', import.meta.url), 'utf8')
  await db.exec(partnerResultsMigration)
  await db.exec(partnerResultsMigration)
  await db.query('SELECT public.backoffice_change($1,$2,$3,$4,$5)', [nicolas,'profile',student,JSON.stringify({ first_name: 'Nicolas' }),'Test'])
  const auditPermissions = (await db.query("SELECT has_table_privilege('service_role','public.backoffice_audit','SELECT') AS read, has_table_privilege('service_role','public.backoffice_audit','INSERT') AS append, has_table_privilege('service_role','public.backoffice_audit','UPDATE,DELETE,TRUNCATE') AS modify")).rows[0]
  assert.deepEqual(auditPermissions,{ read:true,append:true,modify:false })
  const rpc = async (sql, parameters = []) => (await db.query(sql, parameters)).rows[0].result
  const users = await rpc('SELECT public.backoffice_users($1,$2,$3,$4,$5) AS result', ['', 'all', 'all', 50, 1000])
  assert.equal(users.total, 1004)
  assert.equal(users.items.length, 4)
  const overview = await rpc('SELECT public.backoffice_overview() AS result')
  assert.equal(overview.users, 1004)
  assert.equal(overview.results, 1)
  const results = await rpc('SELECT public.backoffice_results() AS result')
  assert.equal(results.items[0].email, 'student@example.com')
  const change = (kind, id, patch) => rpc('SELECT public.backoffice_change($1,$2,$3,$4,$5) AS result', [joris,kind,id,JSON.stringify(patch),'Test'])
  const partnerDisplay = await change('partner',partner,{ show_in_results:false,highlight_in_results:false,results_priority:40 })
  assert.equal(partnerDisplay.show_in_results,false)
  assert.equal(partnerDisplay.highlight_in_results,false)
  assert.equal(partnerDisplay.results_priority,40)
  assert.ok((await db.query("SELECT changed_fields FROM backoffice_audit WHERE resource_id=$1 ORDER BY id DESC LIMIT 1",[partner])).rows[0].changed_fields.includes('results_priority'))
  const displayAuditBefore = (await db.query('SELECT count(*)::int AS count FROM backoffice_audit')).rows[0].count
  await assert.rejects(change('partner',partner,{ results_priority:101 }), /check constraint/)
  assert.equal((await db.query('SELECT count(*)::int AS count FROM backoffice_audit')).rows[0].count,displayAuditBefore)
  const createdPartner = await change('partner',null,{ school_name:'School',formation_name:'New Bachelor',city:'Paris',show_in_results:false,highlight_in_results:true,results_priority:25 })
  assert.equal(createdPartner.results_priority,25)
  assert.equal(createdPartner.show_in_results,false)
  await db.exec('SET ROLE authenticated')
  try { await assert.rejects(db.query('UPDATE ecoles_partenaires SET results_priority=100'), /permission denied/) }
  finally { await db.exec('RESET ROLE') }
  await change('profile',student,{ first_name: 'Corrected' })
  assert.equal((await db.query('SELECT first_name FROM profiles WHERE id=$1',[student])).rows[0].first_name,'Corrected')
  const auditBefore = (await db.query('SELECT count(*)::int AS count FROM backoffice_audit')).rows[0].count
  await assert.rejects(change('profile',student,{ contact_preference: true }), /INVALID_FIELD/)
  assert.equal((await db.query('SELECT count(*)::int AS count FROM backoffice_audit')).rows[0].count,auditBefore)
  await change('school_approve','1',{})
  assert.ok((await db.query('SELECT approved_at FROM companies')).rows[0].approved_at)
  assert.deepEqual((await db.query("SELECT changed_fields FROM backoffice_audit WHERE action='update:school_approve'")).rows[0].changed_fields,['approved_at'])
  const custom = await change('custom',null,{ company_id: 1, title: 'Private formation' })
  await change('custom',String(custom.id),{ is_published: false })
  await change('partner',partner,{ is_active: false })
  await assert.rejects(db.query('SELECT public.backoffice_submit_partner($1,$2)',[student,partner]), /PARTNER_UNAVAILABLE/)
  await change('partner',partner,{ is_active: true })
  await db.query('SELECT public.backoffice_submit_partner($1,$2)',[student,partner])
  await change('partner',partner,{ is_active: false })
  assert.equal((await db.query('SELECT count(*)::int AS count FROM contact_submitted')).rows[0].count,1)
  await assert.rejects(change('partner',partner,{ school_name: 'Renamed' }), /CANONICAL_SCHOOL_NAME_READ_ONLY/)
  const asStudent = async (sql) => {
    await db.exec(`SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub','${student}',false);`)
    try { return await db.query(sql) } finally { await db.exec('RESET ROLE') }
  }
  await assert.rejects(asStudent('SELECT public.backoffice_users()'), /permission denied/)
  await assert.rejects(asStudent('SELECT * FROM public.backoffice_account_suspensions'), /permission denied/)
  await assert.rejects(asStudent("UPDATE companies SET approved_at=now() WHERE id=1"), /permission denied/)
  await assert.rejects(asStudent(`INSERT INTO contact_submitted(user_id,formation_id) VALUES('${student}','${partner}')`), /row-level security/)
  await asStudent("UPDATE companies SET contact_first_name='Contact' WHERE id=1")
  const pending = await rpc('SELECT public.backoffice_account_change($1,$2,$3,$4) AS result',[joris,student,true,'Test suspension'])
  assert.equal(pending.is_suspended,true)
  assert.equal((await asStudent('SELECT * FROM profiles')).rows.length,0)
  await assert.rejects(asStudent(`INSERT INTO profiles(id) VALUES('${student}')`),/row-level security/)
  await assert.rejects(rpc('SELECT public.backoffice_account_change($1,$2,$3,$4) AS result',[joris,nicolas,true,'Forbidden']),/PROTECTED_ADMIN_ACCOUNT/)
  const restoring = await rpc('SELECT public.backoffice_account_change($1,$2,$3,$4) AS result',[joris,student,false,'Test reactivation'])
  assert.equal(restoring.is_suspended,true)
  await assert.rejects(rpc('SELECT public.backoffice_account_change($1,$2,$3,$4,$5) AS result',[joris,student,true,'Stale',pending.revision]),/ACCOUNT_STATE_CHANGED/)
  await rpc('SELECT public.backoffice_account_change($1,$2,$3,$4,$5) AS result',[joris,student,false,'Test reactivation',restoring.revision])
  assert.equal((await asStudent('SELECT * FROM profiles')).rows.length,1)
  await change('school_revoke','1',{})
  assert.equal((await db.query('SELECT approved_at FROM companies')).rows[0].approved_at,null)
  const growthMigration = await readFile(new URL('../database/migration_backoffice_student_growth.sql', import.meta.url), 'utf8')
  await db.exec(growthMigration)
  await db.exec(growthMigration)
  await db.exec("SET TIME ZONE 'Pacific/Honolulu'")
  await db.exec(`UPDATE auth.users SET created_at=(timezone('UTC',now())::date - 60)::timestamp AT TIME ZONE 'UTC' WHERE email LIKE 'fixture-%';
    INSERT INTO auth.users(id,email,created_at) VALUES
      ('55555555-5555-4555-8555-555555555555','older@example.com',(timezone('UTC',now())::date - 40)::timestamp AT TIME ZONE 'UTC'),
      ('66666666-6666-4666-8666-666666666666','yesterday@example.com',(timezone('UTC',now())::date - 1)::timestamp AT TIME ZONE 'UTC'),
      ('77777777-7777-4777-8777-777777777777','today@example.com',now()),
      ('88888888-8888-4888-8888-888888888888','member@example.com',now()),
      ('99999999-9999-4999-8999-999999999999','future@example.com',(timezone('UTC',now())::date + 2)::timestamp AT TIME ZONE 'UTC');
    INSERT INTO school_portal_members(company_id,user_id) VALUES(1,'88888888-8888-4888-8888-888888888888');`)
  const growth = await rpc('SELECT public.backoffice_student_growth(30) AS result')
  const todayUTC = new Date().toISOString().slice(0,10)
  assert.equal(growth.points.length,30)
  assert.equal(growth.points.at(-1).date,todayUTC)
  assert.equal(growth.points[0].date,new Date(Date.parse(`${todayUTC}T00:00:00Z`) - 29*86400000).toISOString().slice(0,10))
  assert.equal(growth.points[0].total,1002)
  assert.equal(growth.points[0].registrations,0)
  assert.equal(growth.points.at(-2).registrations,1)
  assert.equal(growth.points.at(-1).registrations,1)
  assert.equal(growth.totalStudents,1004)
  assert.equal(growth.newStudents,2)
  assert.equal((await rpc('SELECT public.backoffice_student_growth(90) AS result')).points.length,90)
  assert.equal((await rpc('SELECT public.backoffice_student_growth(365) AS result')).points.length,365)
  await assert.rejects(db.query('SELECT public.backoffice_student_growth(999)'),/INVALID_PERIOD/)
  await assert.rejects(db.query('SELECT public.backoffice_student_growth(NULL)'),/INVALID_PERIOD/)
  await assert.rejects(asStudent('SELECT public.backoffice_student_growth(30)'),/permission denied/)
  await db.exec(`CREATE TABLE public.informations_complementaires(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,user_id uuid,question_id text,answer_text text,created_at timestamptz DEFAULT now());
    INSERT INTO public.informations_complementaires(user_id,question_id,answer_text)
      SELECT id,'orientation_final_selection','[{"id":"formation-1","type":"formation","title":"BTS Informatique","subtitle":"Universite Exemple","requestMoreInformation":true}]'
      FROM auth.users WHERE email LIKE 'fixture-%';`)
  const selectionsMigration = await readFile(new URL('../database/migration_backoffice_selections.sql', import.meta.url), 'utf8')
  await db.exec(selectionsMigration)
  await db.exec(selectionsMigration)
  await db.query(`INSERT INTO informations_complementaires(user_id,question_id,answer_text,created_at) VALUES
    ($1,'orientation_final_selection',$2,now()-interval '1 day'),($1,'orientation_final_selection',$3,now())`,[student,
    JSON.stringify([{ id:'old',type:'formation',title:'Old choice',requestMoreInformation:true }]),
    JSON.stringify({ candidates:[{ id:'chosen',type:'formation',title:'Chosen current',requestMoreInformation:true },{ id:'chosen',type:'formation',title:'Chosen current',requestMoreInformation:true },{ id:'ignored',type:'formation',title:'Not chosen',requestMoreInformation:false },{ id:'job',type:'metier',title:'Not formation',requestMoreInformation:true }] })])
  const selections = await rpc('SELECT public.backoffice_selections() AS result')
  assert.equal(selections.total,1003)
  assert.equal(selections.totalUsers,1002)
  assert.equal(selections.items.length,50)
  assert.equal((await rpc("SELECT public.backoffice_selections('','all',50,1000) AS result")).items.length,3)
  const personal = await rpc("SELECT public.backoffice_selections('','all',50,0,$1) AS result",[student])
  assert.equal(personal.total,2)
  assert.equal(personal.items.find((item) => item.source === 'orientation').formation_name,'Chosen current')
  assert.equal(personal.items.find((item) => item.source === 'partner').formation_name,'Bachelor')
  assert.equal((await rpc("SELECT public.backoffice_selections('Chosen current') AS result")).total,1)
  assert.equal((await rpc("SELECT public.backoffice_selections('Old choice') AS result")).total,0)
  assert.equal((await rpc("SELECT public.backoffice_selections('','partner') AS result")).total,1)
  await db.query("INSERT INTO informations_complementaires(user_id,question_id,answer_text,created_at) VALUES($1,'orientation_final_selection','broken JSON',now()+interval '1 second')",[student])
  assert.equal((await rpc("SELECT public.backoffice_selections('','orientation',50,0,$1) AS result",[student])).total,0)
  await assert.rejects(asStudent('SELECT public.backoffice_selections()'),/permission denied/)
  await assert.rejects(asStudent("SELECT public.backoffice_selected_candidates('[]')"),/permission denied/)
  console.log('Back-office PostgreSQL functions, student growth/UTC/exclusions, pagination >1000, atomic audit, suspension and RLS verified.')
} finally {
  await db.close()
}